--liquibase formatted.sql
--changeset michael.cawayan:MONITOR.GET_LOG_IF145_ID contextFilter:PH endDelimiter:/ runOnChange:true

CREATE OR REPLACE EDITIONABLE VIEW "MONITOR"."V_GET_LOG_IF145_ID" ("LOG_CONTRACT_MIS_ID") 
AS select MONITOR.GET_IF145_ID from DUAL
/
GRANT SELECT ON "MONITOR"."V_GET_LOG_IF145_ID" TO MA_TEMP
/
GRANT SELECT ON "MONITOR"."V_GET_LOG_IF145_ID" TO HCI_RO_MONITOR
/
GRANT SELECT ON "MONITOR"."V_GET_LOG_IF145_ID" TO HCI_APP_SELECT
/
GRANT SELECT ON "MONITOR"."V_GET_LOG_IF145_ID" TO APPSUPPORT
/