--liquibase formatted.sql
--changeset michael.cawayan:MONITOR.V_RTDM_LOG_IF145_CONTRACT_MISTAKE contextFilter:PH endDelimiter:/ runOnChange:true

CREATE OR REPLACE EDITIONABLE VIEW "MONITOR"."V_RTDM_LOG_IF145_CONTRACT_MISTAKE" (
    CORRELATION_ID
, EVENT_NAME
, EVENT_TIMESTAMP
, STATUS
, STATUS_DESCRIPTION
, RTDM_HOSTNAME
, LOG_SOURCE
,TCKATTACHMENTSCOMMENT
,TCKATTACHMENTSEXTERNALID
,TCKATTACHMENTSFILENAME
,TCKCATEGORYCODE
,TCKCREATEDBYUID
,TCKCREATIONDATE
,CREATED_DTTM
,UPDATED_DTTM
,TCKDEPARTMENTCODE
,TCKDEPARTMENTFRONTOFFICEFLAG
,TCKDESCRIPTION
,TCKID
,TCKMODIFICATIONDATE
,TCKMODIFIEDBY
,TCKPRIORITYCODE
,TCKRELATEDSUBJECTSCODE
,TCKRELATEDSUBJECTSTYPE
,TCKRESOLUTIONTIME
,TCKRESPONSETIME
,TCKSTATUSCODE
,TCKTRANSITIONSASSIGNEDTO
,TCKTRANSITIONSCOMMENT
,TCKTRANSITIONSCREATEDBYUID
,TCKTRANSITIONSDEPARTMENTCODE
,TCKTRANSITIONSDEPTFRONTOFFICEFLG
,TCKTRANSITIONSORIGINATEDBYUID
,TCKTRANSITIONSSTATUSCODE
,TCKTYPECODE
,TCKTYPESPECCODE
,TCKTRANSITIONSCREATIONDATE
    ) 
AS SELECT 
CORRELATION_ID
, EVENT_NAME
, EVENT_TIMESTAMP
, STATUS
, STATUS_DESCRIPTION
, RTDM_HOSTNAME
,LOG_SOURCE
,TCKATTACHMENTSCOMMENT
,TCKATTACHMENTSEXTERNALID
,TCKATTACHMENTSFILENAME
,TCKCATEGORYCODE
,TCKCREATEDBYUID
,TCKCREATIONDATE
,CREATED_DTTM
,UPDATED_DTTM
,TCKDEPARTMENTCODE
,TCKDEPARTMENTFRONTOFFICEFLAG
,TCKDESCRIPTION
,TCKID
,TCKMODIFICATIONDATE
,TCKMODIFIEDBY
,TCKPRIORITYCODE
,TCKRELATEDSUBJECTSCODE
,TCKRELATEDSUBJECTSTYPE
,TCKRESOLUTIONTIME
,TCKRESPONSETIME
,TCKSTATUSCODE
,TCKTRANSITIONSASSIGNEDTO
,TCKTRANSITIONSCOMMENT
,TCKTRANSITIONSCREATEDBYUID
,TCKTRANSITIONSDEPARTMENTCODE
,TCKTRANSITIONSDEPTFRONTOFFICEFLG
,TCKTRANSITIONSORIGINATEDBYUID
,TCKTRANSITIONSSTATUSCODE
,TCKTYPECODE
,TCKTYPESPECCODE
,TCKTRANSITIONSCREATIONDATE
FROM monitor.RTDM_LOG_IF145_CONTRACT_MISTAKE
WHERE 1=2
/
GRANT SELECT, INSERT, UPDATE, DELETE ON MONITOR.V_RTDM_LOG_IF145_CONTRACT_MISTAKE TO ESP_USER
/
GRANT SELECT ON MONITOR.V_RTDM_LOG_IF145_CONTRACT_MISTAKE TO HCI_RO_MONITOR
/