--liquibase formatted.sql
--changeset michael.cawayan:MONITOR.IOIT_V_RTDM_LOG_IF145_CONTRACT_MISTAKE contextFilter:PH endDelimiter:/ runOnChange:true

CREATE OR REPLACE EDITIONABLE TRIGGER "MONITOR"."IOIT_V_RTDM_LOG_IF145_CONTRACT_MISTAKE" 
INSTEAD OF INSERT ON monitor.V_RTDM_LOG_IF145_CONTRACT_MISTAKE
FOR EACH ROW
BEGIN
  MERGE INTO monitor.RTDM_LOG_IF145_CONTRACT_MISTAKE t
  USING
  (
    SELECT
      :NEW.correlation_id AS correlation_id
      ,:NEW.event_name AS event_name
	    ,:NEW.EVENT_TIMESTAMP AS EVENT_TIMESTAMP
      ,:NEW.STATUS AS STATUS
      ,:NEW.STATUS_DESCRIPTION AS STATUS_DESCRIPTION
      ,:NEW.rtdm_hostname AS rtdm_hostname
      ,:NEW.LOG_SOURCE AS LOG_SOURCE
,:NEW.TCKATTACHMENTSCOMMENT AS TCKATTACHMENTSCOMMENT
,:NEW.TCKATTACHMENTSEXTERNALID AS TCKATTACHMENTSEXTERNALID
,:NEW.TCKATTACHMENTSFILENAME AS TCKATTACHMENTSFILENAME
,:NEW.TCKCATEGORYCODE AS TCKCATEGORYCODE
,:NEW.TCKCREATEDBYUID AS TCKCREATEDBYUID
,:NEW.CREATED_DTTM AS CREATED_DTTM
,:NEW.UPDATED_DTTM AS UPDATED_DTTM
,:NEW.TCKDEPARTMENTCODE AS TCKDEPARTMENTCODE
,:NEW.TCKDEPARTMENTFRONTOFFICEFLAG AS TCKDEPARTMENTFRONTOFFICEFLAG
,:NEW.TCKDESCRIPTION AS TCKDESCRIPTION
,:NEW.TCKID AS TCKID
,:NEW.TCKMODIFICATIONDATE AS TCKMODIFICATIONDATE
,:NEW.TCKMODIFIEDBY AS TCKMODIFIEDBY
,:NEW.TCKPRIORITYCODE AS TCKPRIORITYCODE
,:NEW.TCKRELATEDSUBJECTSCODE AS TCKRELATEDSUBJECTSCODE
,:NEW.TCKRELATEDSUBJECTSTYPE AS TCKRELATEDSUBJECTSTYPE
,:NEW.TCKRESOLUTIONTIME AS TCKRESOLUTIONTIME
,:NEW.TCKRESPONSETIME AS TCKRESPONSETIME
,:NEW.TCKSTATUSCODE AS TCKSTATUSCODE
,:NEW.TCKTRANSITIONSASSIGNEDTO AS TCKTRANSITIONSASSIGNEDTO
,:NEW.TCKTRANSITIONSCOMMENT AS TCKTRANSITIONSCOMMENT
,:NEW.TCKTRANSITIONSCREATEDBYUID AS TCKTRANSITIONSCREATEDBYUID
,:NEW.TCKTRANSITIONSDEPARTMENTCODE AS TCKTRANSITIONSDEPARTMENTCODE
,:NEW.TCKTRANSITIONSDEPTFRONTOFFICEFLG AS TCKTRANSITIONSDEPTFRONTOFFICEFLG
,:NEW.TCKTRANSITIONSORIGINATEDBYUID AS TCKTRANSITIONSORIGINATEDBYUID
,:NEW.TCKTRANSITIONSSTATUSCODE AS TCKTRANSITIONSSTATUSCODE
,:NEW.TCKTYPECODE AS TCKTYPECODE
,:NEW.TCKTYPESPECCODE AS TCKTYPESPECCODE
,:NEW.TCKTRANSITIONSCREATIONDATE AS TCKTRANSITIONSCREATIONDATE
      FROM dual
  ) s
  ON (t.correlation_id = s.correlation_id)
  WHEN MATCHED THEN
    UPDATE
    SET
	  t.event_name = s.event_name,
	  t.EVENT_TIMESTAMP = s.EVENT_TIMESTAMP,
      t.STATUS = s.STATUS, 
      t.STATUS_DESCRIPTION = s.STATUS_DESCRIPTION,
      t.rtdm_hostname = s.rtdm_hostname, 
      t.log_source = 'ESP'
      ,t.TCKATTACHMENTSCOMMENT      = s.TCKATTACHMENTSCOMMENT           
,t.TCKATTACHMENTSEXTERNALID         = s.TCKATTACHMENTSEXTERNALID        
,t.TCKATTACHMENTSFILENAME           = s.TCKATTACHMENTSFILENAME          
,t.TCKCATEGORYCODE                  = s.TCKCATEGORYCODE                 
,t.TCKCREATEDBYUID                  = s.TCKCREATEDBYUID                 
,t.CREATED_DTTM                     = s.CREATED_DTTM                    
,t.UPDATED_DTTM                     = s.UPDATED_DTTM                    
,t.TCKDEPARTMENTCODE                = s.TCKDEPARTMENTCODE               
,t.TCKDEPARTMENTFRONTOFFICEFLAG     = s.TCKDEPARTMENTFRONTOFFICEFLAG    
,t.TCKDESCRIPTION                   = s.TCKDESCRIPTION                  
,t.TCKID                            = s.TCKID                           
,t.TCKMODIFICATIONDATE              = s.TCKMODIFICATIONDATE             
,t.TCKMODIFIEDBY                    = s.TCKMODIFIEDBY                   
,t.TCKPRIORITYCODE                  = s.TCKPRIORITYCODE                 
,t.TCKRELATEDSUBJECTSCODE           = s.TCKRELATEDSUBJECTSCODE          
,t.TCKRELATEDSUBJECTSTYPE           = s.TCKRELATEDSUBJECTSTYPE          
,t.TCKRESOLUTIONTIME                = s.TCKRESOLUTIONTIME               
,t.TCKRESPONSETIME                  = s.TCKRESPONSETIME                 
,t.TCKSTATUSCODE                    = s.TCKSTATUSCODE                   
,t.TCKTRANSITIONSASSIGNEDTO         = s.TCKTRANSITIONSASSIGNEDTO        
,t.TCKTRANSITIONSCOMMENT            = s.TCKTRANSITIONSCOMMENT           
,t.TCKTRANSITIONSCREATEDBYUID       = s.TCKTRANSITIONSCREATEDBYUID      
,t.TCKTRANSITIONSDEPARTMENTCODE     = s.TCKTRANSITIONSDEPARTMENTCODE    
,t.TCKTRANSITIONSDEPTFRONTOFFICEFLG = s.TCKTRANSITIONSDEPTFRONTOFFICEFLG
,t.TCKTRANSITIONSORIGINATEDBYUID    = s.TCKTRANSITIONSORIGINATEDBYUID   
,t.TCKTRANSITIONSSTATUSCODE         = s.TCKTRANSITIONSSTATUSCODE        
,t.TCKTYPECODE                      = s.TCKTYPECODE                     
,t.TCKTYPESPECCODE                  = s.TCKTYPESPECCODE                 
,t.TCKTRANSITIONSCREATIONDATE       = s.TCKTRANSITIONSCREATIONDATE
	WHERE t.STATUS IS NULL
  WHEN NOT MATCHED THEN
    INSERT (
        t.LOG_CONTRACT_MIS_ID
        , t.correlation_id
        , t.event_name
        , t.EVENT_TIMESTAMP
        , t.STATUS
        , t.STATUS_DESCRIPTION
        , t.rtdm_hostname
        , t.log_source
        ,t.TCKATTACHMENTSCOMMENT           
,t.TCKATTACHMENTSEXTERNALID        
,t.TCKATTACHMENTSFILENAME          
,t.TCKCATEGORYCODE                 
,t.TCKCREATEDBYUID                 
,t.CREATED_DTTM                    
,t.UPDATED_DTTM                    
,t.TCKDEPARTMENTCODE               
,t.TCKDEPARTMENTFRONTOFFICEFLAG    
,t.TCKDESCRIPTION                  
,t.TCKID                           
,t.TCKMODIFICATIONDATE             
,t.TCKMODIFIEDBY                   
,t.TCKPRIORITYCODE                 
,t.TCKRELATEDSUBJECTSCODE          
,t.TCKRELATEDSUBJECTSTYPE          
,t.TCKRESOLUTIONTIME               
,t.TCKRESPONSETIME                 
,t.TCKSTATUSCODE                   
,t.TCKTRANSITIONSASSIGNEDTO        
,t.TCKTRANSITIONSCOMMENT           
,t.TCKTRANSITIONSCREATEDBYUID      
,t.TCKTRANSITIONSDEPARTMENTCODE    
,t.TCKTRANSITIONSDEPTFRONTOFFICEFLG
,t.TCKTRANSITIONSORIGINATEDBYUID   
,t.TCKTRANSITIONSSTATUSCODE        
,t.TCKTYPECODE                     
,t.TCKTYPESPECCODE                 
,t.TCKTRANSITIONSCREATIONDATE      
)
    VALUES (
        monitor.GET_IF145_ID
        , s.correlation_id
        , s.event_name
        , s.EVENT_TIMESTAMP
        , s.STATUS
        , s.STATUS_DESCRIPTION
        , s.rtdm_hostname
        , 'ESP'
        ,s.TCKATTACHMENTSCOMMENT           
,s.TCKATTACHMENTSEXTERNALID        
,s.TCKATTACHMENTSFILENAME          
,s.TCKCATEGORYCODE                 
,s.TCKCREATEDBYUID                 
,s.CREATED_DTTM                    
,s.UPDATED_DTTM                    
,s.TCKDEPARTMENTCODE               
,s.TCKDEPARTMENTFRONTOFFICEFLAG    
,s.TCKDESCRIPTION                  
,s.TCKID                           
,s.TCKMODIFICATIONDATE             
,s.TCKMODIFIEDBY                   
,s.TCKPRIORITYCODE                 
,s.TCKRELATEDSUBJECTSCODE          
,s.TCKRELATEDSUBJECTSTYPE          
,s.TCKRESOLUTIONTIME               
,s.TCKRESPONSETIME                 
,s.TCKSTATUSCODE                   
,s.TCKTRANSITIONSASSIGNEDTO        
,s.TCKTRANSITIONSCOMMENT           
,s.TCKTRANSITIONSCREATEDBYUID      
,s.TCKTRANSITIONSDEPARTMENTCODE    
,s.TCKTRANSITIONSDEPTFRONTOFFICEFLG
,s.TCKTRANSITIONSORIGINATEDBYUID   
,s.TCKTRANSITIONSSTATUSCODE        
,s.TCKTYPECODE                     
,s.TCKTYPESPECCODE                 
,s.TCKTRANSITIONSCREATIONDATE      
);
END;
/
ALTER TRIGGER "MONITOR"."IOIT_V_RTDM_LOG_IF145_CONTRACT_MISTAKE" ENABLE
/