--liquibase formatted.sql
--changeset michael.cawayan:MONITOR.IF145_ID_SEQ contextFilter:PH endDelimiter:/ runOnChange:true

CREATE SEQUENCE MONITOR.IF145_ID_SEQ MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL 
/
GRANT SELECT ON MONITOR.IF145_ID_SEQ TO HCI_RO_MONITOR
/
GRANT SELECT ON MONITOR.IF145_ID_SEQ TO MA_TEMP
/
GRANT SELECT ON MONITOR.IF145_ID_SEQ TO HCI_APP_SELECT
/
GRANT SELECT ON MONITOR.IF145_ID_SEQ TO APPSUPPORT
/